CREATE TABLE CUSTOMERS
(EMAIL CHAR(60) PRIMARY KEY,
FIRSTNAME CHAR(30) NOT NULL,
LASTNAME CHAR(30) NOT NULL);

CREATE TABLE ROOMS
(ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TYPE CHAR(15) NOT NULL,
NUMBEDS INT NOT NULL,
PRICE INT NOT NULL);

CREATE TABLE CITIES
(ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CITY CHAR(9));

CREATE TABLE STAFF
(ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
USERNAME VARCHAR(60),
PASSWORD VARCHAR(60)
);

CREATE TABLE BOOKINGS
(ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CHECKIN BIGINT NOT NULL,
CHECKOUT BIGINT NOT NULL,
CUSTID CHAR(60) NOT NULL CONSTRAINT custref REFERENCES CUSTOMERS(EMAIL),
CITYID INT NOT NULL CONSTRAINT cityref REFERENCES CITIES(ID),
ROOMID INT NOT NULL CONSTRAINT roomref REFERENCES ROOMS(ID),
EXTRABED BOOLEAN,
CARDNUM BIGINT NOT NULL,
PIN INT NOT NULL
FAIR INT
);

CREATE TABLE DISCOUNT
(
ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STARTDATE BIGINT NOT NULL,
ENDDATE BIGINT NOT NULL,
ROOMTYPE VARCHAR(20),
DISCOUNTRATE INT
);

INSERT INTO CITIES (CITY) VALUES
('Sydney'),('Brisbane'),('Melbourne'),('Adelaide'),('Hobart');

INSERT INTO ROOMS(TYPE, NUMBEDS, PRICE)
VALUES ('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Single',1,70),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Twin Bed',2,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Queen',1,120),
('Executive',1,180),
('Executive',1,180),
('Executive',1,180),
('Executive',1,180),
('Executive',1,180),
('Suite',2,300);
('Suite',2,300);
